### ISSUE TITLE
Running on Mars (PDT 3.6.0 shipped) is broken

### ISSUE THREAD

**Issue by maikgreubel** [piece/makegood#81]
Here is the status report:

    ------
    STATUS
    ------
    pluginId            org.eclipse.core.jobs
    pluginVersion       3.7.0.v20150330-2103
    code                2
    severity            4
    message             An internal error occurred during: "Launching AbstractDatabaseTestCase".
    fingerprint         c3db98aa
    
    Exception:java.lang.NoSuchMethodError: org.eclipse.php.internal.debug.core.preferences.PHPDebuggersRegistry.getDebuggerConfiguration(Ljava/lang/String;)Lorg/eclipse/php/internal/debug/core/debugger/AbstractDebuggerConfiguration;
    	 at HIDDEN.HIDDEN(HIDDEN:-1)
    	 at HIDDEN.HIDDEN(HIDDEN:-1)
    	 at HIDDEN.HIDDEN(HIDDEN:-1)
    	 at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:812)
    	 at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    	 at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    	 at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    
    ------
    REPORT
    ------
    anonymousId         443bcb70-f4e8-4aae-bc9c-6a7d621c64f5
    name                Maik Greubel
    email               greubel@nkey.de
    comment             The problematic package 'org.eclipse.php.internal.debug.core.preferences' may originate in the following bundles:
      org.eclipse.php.debug.core 3.6.0.201507021953, from which the following bundles present on the stack trace import it:
        com.piece_framework.makegood.launch 3.1.1.v201409021510
    
    eclipseBuildId      4.5.0.I20150603-2000
    eclipseProduct      org.eclipse.epp.package.php.product
    javaRuntimeVersion  1.8.0_20-b26
    osgiWs              win32
    osgiOs              Windows7
    osgiOsVersion       6.1.0
    osgiArch            x86_64
    logMessage          false
    ignoreSimilar       false
    
    -------
    BUNDLES
    -------
    name                com.piece_framework.makegood.launch
    version             3.1.1.v201409021510
    
    name                org.eclipse.core.jobs
    version             3.7.0.v20150330-2103
    
    name                org.eclipse.debug.core
    version             3.10.0.v20150303-1130
    
    name                org.eclipse.debug.ui
    version             3.11.0.v20150514-0917

When I push the run button, the error is shown, second start is not possible because makegood has its internal status not resetted and shows that an instance already is running.

Here a detailed stack trace:

    java.lang.NoSuchMethodError: org.eclipse.php.internal.debug.core.preferences.PHPDebuggersRegistry.getDebuggerConfiguration(Ljava/lang/String;)Lorg/eclipse/php/internal/debug/core/debugger/AbstractDebuggerConfiguration;
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.rewriteBasicConfigurationAttributes(MakeGoodLaunchConfigurationDelegate.java:286)
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.createConfiguration(MakeGoodLaunchConfigurationDelegate.java:267)
	at com.piece_framework.makegood.launch.MakeGoodLaunchConfigurationDelegate.getLaunch(MakeGoodLaunchConfigurationDelegate.java:85)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:812)
	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
	at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by maikgreubel** [comment]
Sorry for the duplicate, the https://github.com/piece/makegood/releases/tag/v3.2.0-dev1 solves my issue.

**Comment by iteman** [comment]
@maikgreubel Thank you! :smile:
